version: "3.2"
services:
  frontend:
    tty: true
    stdin_open: true
    user: root
    working_dir: /app
    build:
      context: .
      dockerfile: frontend/docker/cpu/Dockerfile
      target: dev
      # secrets:
      #   - github_token
      args:
        progress: plain
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "8080:8080"
    command:
      poetry run streamlit run src/meal_shield/app.py --server.port 8080
    environment:
        PYTHONPATH: "/app/src"
        PYTHONUNBUFFERED: 1
  backend:
    tty: true
    stdin_open: true
    user: root
    working_dir: /app
    build:
      context: .
      dockerfile: backend/docker/cpu/Dockerfile
      target: dev
      # secrets:
      #   - github_token
      args:
        progress: plain
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - "127.0.0.1:8000:8000"
    # command:
    #   poetry run uvicorn src.meal_shield.app:app --reload --host 0.0.0.0 --port 8000
    environment:
        PYTHONPATH: "/app/src"
        PYTHONUNBUFFERED: 1
# secrets:
#   github_token:
#     file: ${HOME}/.git-credentials
