name: test

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      check-service-test:
        required: false
        default: false
        type: boolean

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Tokyo
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup docker
        shell: bash
        run: |
          docker compose build --progress=plain
          docker compose up -d
      - name: Test
        run: docker compose exec backend poetry run tox
