name: test

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      check-service-test:
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: docker compose up -d --build

      - name: Test
        run: docker compose exec backend poetry run tox
